server:
  port: 8090
  error:
    whitelabel:
      enabled: true

spring:
  datasource:
    username: 'postgre'
    password: 'root'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/socialMediaAuth'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true