server:
  port: 9099
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: config-server
  elasticsearch:
    uris: http://localhost:9200

myapplication:
  elastic-service:
    feign-user: http://localhost:8092/api/v1


# JWT
myjwt:
  secretKey: ${secretKey}
  audience: ${audience}
  issuer: ${issuer}