server:
  port: 8092
  error:
    whitelabel:
      enabled: true

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  datasource:
    username: 'postgres'
    password: 'root'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/socialMediaUser'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:

myredis:
  host: localhost
  port: 6379


# JWT
myjwt:
  secretKey: ${secretKey}
  audience: ${audience}
  issuer: ${issuer}